# Generated by Dockta 0.22.2 at 2021-08-10T21:40:57.344Z
# To stop Dockta generating this file and start editing it yourself,
# rename it to "Dockerfile".

# This tells Docker which base image to use.
FROM ubuntu:19.10

# All installation commands are run as the root user
USER root

# This section installs system packages required for your project
# If you need extra system packages add them here.
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      python3 \
      python3-pip \
 && apt-get autoremove -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# It's good practice to run Docker images as a non-root user.
# This section creates a guest user (if necessary) and sets its home directory as the default working directory.
RUN id -u guest >/dev/null 2>&1 || useradd --create-home --uid 1000 -s /bin/bash guest
WORKDIR /home/guest

# This is a special comment to tell Dockta to manage the build from here on
# dockta

# This section copies package requirement files into the image
COPY .requirements.txt requirements.txt

# This section runs commands to install the packages specified in the requirement file/s
RUN pip3 install --requirement requirements.txt

# This section copies your project's files into the image
COPY src/__init__.py src/__init__.py
COPY src/utils.py src/utils.py

# This sets the default user when the container is run
USER guest
